# Generated by Django 5.1.1 on 2024-09-19 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriprion',
            new_name='Subscription',
        ),
    ]
